<?php
/**
 * Created by PhpStorm.
 * User: Pavel Batanov <pavel@batanov.me>
 * Date: 26.05.2015
 * Time: 10:10
 */

namespace ScayTrase\StoredFormsBundle\Form\Type;

use ScayTrase\StoredFormsBundle\Form\AbstractFieldType;
use Symfony\Component\Form\FormBuilderInterface;

class AbstractEntityFieldType extends AbstractFieldType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder->add('classname', 'text');
    }

}
