ScayTrase\StorableFormsBundle\Entity\FieldValue:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
          type: text
          nullabel: true
    manyToOne:
        field:
          targetEntity: AbstractField
          joinColumn:
            name: type
