ScayTrase\Forms\StorableFormsBundle\Entity\FieldValue:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
          type: string
          length: 2048
    manyToOne:
        field:
          targetEntity: Field
          joinColumn:
            name: type