ScayTrase\StoredFormsBundle\Entity\Field\AbstractField:
    type: entity
    inheritanceType: SINGLE_TABLE
    id:
      id:
        type: guid
        id: true
    fields:
      name:
        type: string
      title:
        type: string
        nullable: true
      help_message:
        type: text
        nullable: true
      required:
        type: boolean
