ScayTrase\StoredFormsBundle\Entity\Field\Type\ChoiceField:
    type: entity
    fields:
        choices:
          type: json_array
        multiple:
          type: boolean
        expanded:
          type: boolean
