ScayTrase\StoredFormsBundle\Entity\Value\AbstractValue:
  type: entity
  inheritanceType: SINGLE_TABLE
  id:
    id:
      type: guid
      id: true

  manyToOne:
    field:
      targetEntity: ScayTrase\StoredFormsBundle\Entity\Field\AbstractField
      joinColumn:
        name: type
