ScayTrase\StoredFormsBundle\Entity\Value\Type\TableRow:
  type: entity
  id:
    id:
      type: guid
      id: true

  manyToMany:
    values:
      targetEntity: ScayTrase\StoredFormsBundle\Entity\Value\AbstractValue
      cascade: [all]
      orphanRemoval: true

  manyToOne:
    table:
      targetEntity: ScayTrase\StoredFormsBundle\Entity\Value\Type\TableValue
      inversedBy: rows
